def local_brief(row,client_context="",goal="Crescita organica"):
    topic=str(row.get("topic","tema")); gap=str(row.get("fresh_research_summary","")) or "Evidenze, esempi e fonti aggiornate"
    cluster=str(row.get("winning_cluster") or row.get("origin_cluster") or "interesse validato")
    entities=str(row.get("entities") or "i protagonisti")
    title=str(row.get("recommended_headline") or f"{topic.title()}: cosa cambia e perché conta adesso")
    decision=str(row.get("editorial_decision") or "Prepara e valida")
    variants=[title,f"{topic.title()}: il dettaglio che cambia lo scenario",f"{topic.title()}: numeri, protagonisti e conseguenze",f"{entities}: cosa sappiamo e cosa può succedere adesso",f"Perché questo sviluppo conta adesso: i fatti e le domande aperte"]
    meta=f"{title}. I fatti verificati, i protagonisti e cosa cambia adesso per il pubblico interessato alla vicenda."
    recipe=str(row.get("title_recipe","") or "").strip()
    why_title=(f"Applica i pattern già vincenti sul sito ({recipe}) mantenendo il legame con «{cluster}»." if recipe
               else f"Mantiene il legame con «{cluster}», apre una domanda informativa e non esaurisce la notizia nel titolo.")
    return {"consiglio_editoriale":decision,"nota_editoriale":str(row.get("editorial_advice") or "Il cluster ha già dimostrato interesse: procedere solo se esiste un trigger fresco e verificabile."),"titolo_scelto":title,"perche_questo_titolo":why_title,"titoli_alternativi":variants,"meta_description":meta[:158],"focus_query":str(row.get("keywords") or topic),"angolo":str(row.get("proposed_argument") or "Sviluppo adiacente con una promessa editoriale distinta"),"differenziazione":str(row.get("differentiation") or gap),"elementi_nuovi":["Il fatto o dato che rende attuale il pezzo","Il protagonista adiacente collegato al cluster vincente","La conseguenza concreta ancora poco coperta"],"struttura_articolo":["Apertura sul fatto nuovo, senza preamboli","Contesto minimo e legame con la storia principale","Dati, dichiarazioni e fonti attribuite","La conseguenza o il punto di svolta","Chiusura sulle domande ancora aperte"],"formato_suggerito":"4-6 paragrafi brevi · mobile-first","timing":str(row.get("urgency") or "Entro 24-48 ore"),"fonti_da_verificare":[x for x in str(row.get("evidence_urls") or "").splitlines() if x][:5],"link_interno":str(row.get("source_url") or row.get("url") or ""),"rischi_note":"Non forzare il titolo oltre i fatti disponibili. Attribuire dichiarazioni e verificare data, fonte primaria e immagini.","azioni_consigliate":["Confermare il trigger con almeno due fonti","Scegliere il titolo dopo il fact-check","Pubblicare nel timing indicato","Misurare CTR e permanenza nelle prime ore"],"scelte_editoriali":[f"Titolo scelto perché replica i tratti già premiati dal pubblico ({recipe})." if recipe else "Titolo scelto per coerenza con il cluster vincente.","Le fonti raccolte dal web vanno verificate una a una prima della scrittura: il motore locale non fa fact-checking.","La bozza pronta per il CMS richiede il motore AI con LLM: le regole locali producono struttura e istruzioni, non testo."],"stima_potenziale":"Non stimabile con le sole regole locali: dipende dal trigger verificato e dalla finestra di pubblicazione.","titolo_consigliato":title,"outline":["Fatto nuovo","Contesto","Evidenze","Conseguenze","Domande aperte"]}
def propose_actions(brief,row):
    title=brief.get("titolo_scelto") or brief.get("titolo_consigliato","nuovo contenuto")
    return [{"azione":"Validazione editoriale del brief","responsabile":"Content strategist","rischio":"Basso","richiede_approvazione":False,"motivo":"Attività interna e reversibile","stato":"Auto-approvata"},{"azione":f"Pubblicare: {title}","responsabile":"Editor / Cliente","rischio":"Medio","richiede_approvazione":True,"motivo":"Azione esterna visibile al pubblico","stato":"In attesa"},{"azione":"Modificare title, meta description e CTA","responsabile":"SEO specialist","rischio":"Medio","richiede_approvazione":True,"motivo":"Può influire su CTR e brand","stato":"In attesa"}]
